from reportlab.lib.units import inch
from reportlab.lib.units import inch
import re
from .models import *
from datetime import datetime


def sanitize_filename(text):

    text = str(text).strip()

    # Replace spaces with underscores
    text = text.replace(" ", "_")

    # Remove invalid filename characters
    text = re.sub(r'[\\/*?:"<>|]', "", text)

    return text


def build_export_filename(request, prefix, extension):

    parts = [prefix]

    customer = request.GET.get("customer")
    payment = request.GET.get("payment")
    session = request.GET.get("session")
    date = request.GET.get("date")
    status = request.GET.get("status")

    if customer:
        try:
            customer_name = Customer.objects.get(id=customer).name
            parts.append(sanitize_filename(customer_name))
        except Customer.DoesNotExist:
            pass

    if payment:
        parts.append(sanitize_filename(payment.capitalize()))

    if session:
        parts.append(sanitize_filename(f"Session{session}"))

    if date:
        parts.append(sanitize_filename(date.capitalize()))

    if status and status != "draft":
        parts.append(sanitize_filename(status.capitalize()))

    parts.append(datetime.now().strftime("%Y-%m-%d_%H-%M"))

    parts = [sanitize_filename(part) for part in parts]

    return "_".join(parts) + f".{extension}" 


def add_page_footer(canvas, doc):

    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    canvas.line(inch,0.75 * inch,doc.pagesize[0] - inch,0.75 * inch)

    canvas.drawString(inch,0.5 * inch,"Generated by POS System")

    canvas.drawRightString(doc.pagesize[0] - inch,0.5 * inch,f"Page {doc.page}")

    canvas.restoreState()