# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineSyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('header', models.TextField(blank=True)),
                ('footer', models.TextField(blank=True)),
                ('show_logo', models.BooleanField(default=True)),
                ('show_qr', models.BooleanField(default=True)),
                ('show_tax_breakdown', models.BooleanField(default=True)),
                ('show_cashier', models.BooleanField(default=True)),
                ('show_customer', models.BooleanField(default=True)),
                ('accent_color', models.CharField(default='#111827', max_length=20)),
                ('columns', models.JSONField(default=list)),
                ('paper', models.CharField(default='80mm', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashDrawerEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('no_sale', 'No sale'), ('payout', 'Payout'), ('drop', 'Drop')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawer_events', to='pos.cashsession')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('returned_items', models.JSONField(default=list)),
                ('replacement_items', models.JSONField(default=list)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchanges', to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='Layaway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layaways', to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='LayawayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(max_length=20)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('layaway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='pos_core.layaway')),
            ],
        ),
        migrations.CreateModel(
            name='ParkedOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=60)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('parked', 'Parked'), ('resumed', 'Resumed'), ('expired', 'Expired')], default='parked', max_length=20)),
                ('parked_at', models.DateTimeField(auto_now_add=True)),
                ('resumed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.customer')),
                ('parked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parked_orders', to='pos.cashsession')),
            ],
        ),
        migrations.CreateModel(
            name='SplitBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('share_count', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='pos.order')),
            ],
        ),
        migrations.CreateModel(
            name='SplitBillShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('payment_method', models.CharField(blank=True, max_length=20)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='pos_core.splitbill')),
            ],
        ),
    ]
