# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('pos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='pos.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='pos.supplier'),
        ),
        migrations.AddField(
            model_name='batchmovement',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='catalog.batch'),
        ),
        migrations.AddField(
            model_name='batchmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='batchmovement',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.order'),
        ),
        migrations.AddField(
            model_name='bundlecomponent',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bundle_components', to='pos.product'),
        ),
        migrations.AddField(
            model_name='bundlecomponent',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='catalog.productbundle'),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='pos.product'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants_detail', to='pos.product'),
        ),
        migrations.AddField(
            model_name='bundlecomponent',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='productvariantattribute',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='catalog.productvariant'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serials', to='pos.product'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='sold_in_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serials_sold', to='pos.order'),
        ),
        migrations.AddField(
            model_name='serialnumber',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('product', 'batch_number'), name='unique_product_batch'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('sku', ''), _negated=True), fields=('product', 'sku'), name='unique_variant_sku'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode', ''), _negated=True), fields=('product', 'barcode'), name='unique_variant_barcode'),
        ),
        migrations.AddConstraint(
            model_name='productvariantattribute',
            constraint=models.UniqueConstraint(fields=('variant', 'name'), name='unique_variant_attr_name'),
        ),
        migrations.AddConstraint(
            model_name='serialnumber',
            constraint=models.UniqueConstraint(fields=('product', 'serial_number'), name='unique_product_serial'),
        ),
    ]
