# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('symbol', models.CharField(max_length=10)),
                ('decimals', models.PositiveIntegerField(default=2)),
                ('is_base', models.BooleanField(default=False, help_text='The currency all amounts are stored in')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), help_text='Rate from base → this currency (1 base = rate * this)', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('direction', models.CharField(choices=[('ltr', 'LTR'), ('rtl', 'RTL')], default='ltr', max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserLocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=40)),
                ('time_format', models.CharField(default='HH:mm', max_length=40)),
                ('timezone', models.CharField(default='UTC', max_length=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='i18n_app.currency')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='i18n_app.language')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='locale', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TranslationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(default='common', max_length=60)),
                ('key', models.CharField(max_length=200)),
                ('value', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='i18n_app.language')),
            ],
            options={
                'indexes': [models.Index(fields=['namespace', 'language'], name='i18n_app_tr_namespa_56022a_idx')],
                'unique_together': {('namespace', 'key', 'language')},
            },
        ),
    ]
