# Generated by Django 6.0.6 on 2026-06-24 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_draftorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.draftorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
            ],
        ),
    ]
