# Generated by Django 6.0.6 on 2026-06-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='next_draft_number',
            field=models.IntegerField(default=1),
        ),
    ]
