# Generated by Django 6.0.6 on 2026-06-25 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_cashsession_next_draft_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.customer'),
        ),
    ]
