# Generated by Django 6.0.6 on 2026-06-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_draftorder_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorder',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
