# Generated by Django 6.0.6 on 2026-06-26 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0011_draftorder_note_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
