# Generated by Django 6.0.6 on 2026-06-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0012_order_amount_received_order_change_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, upload_to='company/')),
            ],
        ),
    ]
