# Generated by Django 6.0.6 on 2026-06-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_companysettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('tax_number', models.CharField(blank=True, max_length=100)),
                ('footer_message', models.TextField(blank=True, default='Thank you for your purchase!')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('currency', models.CharField(default='Rs', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='CompanySettings',
        ),
    ]
