# Generated by Django 6.0.6 on 2026-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_company_delete_companysettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='receipt_paper',
            field=models.CharField(choices=[('58mm', '58mm Thermal'), ('80mm', '80mm Thermal'), ('A5', 'A5'), ('A4', 'A4')], default='80mm', max_length=10),
        ),
    ]
