# Generated by Django 6.0.6 on 2026-06-28 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0016_alter_order_status_refund_refunditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('paid', 'Paid'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
