# Generated by Django 6.0.6 on 2026-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0017_alter_order_status_alter_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftorderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
