# Generated by Django 6.0.6 on 2026-06-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_draftorderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='footer_message',
            field=models.TextField(blank=True, default='Thank you for your purchase!'),
        ),
    ]
