# Generated by Django 6.0.6 on 2026-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_remove_refund_footer_message_refund_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refunditem',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
