# Generated by Django 6.0.6 on 2026-06-30 21:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0021_refunditem_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pos.order'),
        ),
    ]
