# Generated by Django 6.0.6 on 2026-07-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0022_alter_refund_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gst',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
