# Generated by Django 6.0.6 on 2026-07-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0024_product_max_stock_product_min_stock_product_unit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sales_price',
        ),
    ]
