# Generated by Django 6.0.6 on 2026-07-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0028_purchaseorder_purchaseorderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='received_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
