# Generated by Django 6.0.6 on 2026-07-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0029_purchaseorderitem_received_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('refund', 'Refund'), ('purchase_return', 'Purchase Return'), ('adjustment', 'Adjustment'), ('damage', 'Damage')], max_length=20),
        ),
    ]
