# Generated by Django 6.0.6 on 2026-07-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0031_purchaseorderitem_returned_quantity_purchasereturn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
