# Generated by Django 6.0.6 on 2026-07-13 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0034_orderitem_image_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
