# Generated by Django 6.0.6 on 2026-07-14 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0035_remove_orderitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='employee_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
