# Generated by Django 6.0.6 on 2026-07-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0045_cashsession_actual_closing_balance_cashsession_notes_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftCard',
        ),
    ]
