# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_taxable', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_tax_collected', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('breakdown_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('mode', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=10)),
                ('compound_style', models.CharField(choices=[('flat', 'Flat (additive)'), ('compound', 'Compound (cascading)')], default='flat', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='TaxExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('customer', 'Customer'), ('product', 'Product'), ('category', 'Category')], max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.category')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.customer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('tax_rate', models.ForeignKey(blank=True, help_text='If blank, exempts from all tax rates', null=True, on_delete=django.db.models.deletion.CASCADE, to='tax.taxrate')),
            ],
        ),
        migrations.CreateModel(
            name='TaxBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_rate_code', models.CharField(blank=True, max_length=20)),
                ('rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('mode', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_breakdowns', to='pos.order')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax.taxrate')),
            ],
        ),
    ]
