# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enterprise', '0001_initial'),
        ('pos', '0001_initial'),
        ('system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='system.store'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_stock', to='pos.product'),
        ),
        migrations.AddField(
            model_name='warehousestock',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_levels', to='enterprise.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='destination_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transfers', to='enterprise.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_stock_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='warehousetransfer',
            name='source_warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transfers', to='enterprise.warehouse'),
        ),
        migrations.AddField(
            model_name='warehousetransferitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product'),
        ),
        migrations.AddField(
            model_name='warehousetransferitem',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='enterprise.warehousetransfer'),
        ),
        migrations.AddConstraint(
            model_name='warehousestock',
            constraint=models.UniqueConstraint(fields=('warehouse', 'product'), name='unique_warehouse_product_stock'),
        ),
        migrations.AddConstraint(
            model_name='warehousetransferitem',
            constraint=models.UniqueConstraint(fields=('transfer', 'product'), name='unique_transfer_product'),
        ),
    ]
