# Generated by Django 6.0.6 on 2026-07-28 19:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pos', '0045_cashsession_actual_closing_balance_cashsession_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABCAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('cumulative_share', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('abc_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abc_records', to='pos.product')),
            ],
            options={
                'ordering': ['-annual_value'],
            },
        ),
        migrations.CreateModel(
            name='CycleCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In progress'), ('reconciled', 'Reconciled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cycle_counts', to='pos.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='CycleCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('variance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory2.cyclecount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryAgingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aging_snapshots', to='pos.product')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_point', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('target_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('auto_generate_po', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='pos.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.supplier')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reorder_rules', to='pos.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('released', 'Released'), ('fulfilled', 'Fulfilled')], default='active', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='pos.product')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='pos.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='BinLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=60)),
                ('aisle', models.CharField(blank=True, max_length=60)),
                ('rack', models.CharField(blank=True, max_length=60)),
                ('bin', models.CharField(blank=True, max_length=60)),
                ('code', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bins', to='pos.warehouse')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('warehouse', 'code'), name='unique_bin_code')],
            },
        ),
    ]
