# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sales_query', 'Sales query'), ('reorder', 'Reorder'), ('summary', 'Summary')], max_length=20, unique=True)),
                ('template', models.TextField(help_text='Use {question} / {context} placeholders')),
                ('response_json_schema', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReorderSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_qty', models.PositiveIntegerField()),
                ('current_stock', models.IntegerField(default=0)),
                ('avg_daily_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('days_of_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lead_time_days', models.PositiveIntegerField(default=7)),
                ('confidence', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('model', models.CharField(blank=True, max_length=60)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
