# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('shopify', 'Shopify'), ('woocommerce', 'WooCommerce'), ('quickbooks', 'QuickBooks'), ('xero', 'Xero')], max_length=20)),
                ('name', models.CharField(max_length=120)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kind', 'name'],
                'unique_together': {('kind', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound')], max_length=10)),
                ('entity_type', models.CharField(max_length=60)),
                ('entity_id', models.CharField(blank=True, max_length=60)),
                ('remote_id', models.CharField(blank=True, max_length=60)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='integrations.integration')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['integration', 'status'], name='integration_integra_68a376_idx'), models.Index(fields=['entity_type', 'entity_id'], name='integration_entity__7a1b70_idx')],
            },
        ),
        migrations.CreateModel(
            name='SyncMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=60)),
                ('local_id', models.CharField(max_length=60)),
                ('remote_id', models.CharField(max_length=60)),
                ('last_hash', models.CharField(blank=True, help_text='Content hash to detect changes', max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='integrations.integration')),
            ],
            options={
                'indexes': [models.Index(fields=['integration', 'entity_type', 'remote_id'], name='integration_integra_43cbc1_idx')],
                'unique_together': {('integration', 'entity_type', 'local_id')},
            },
        ),
    ]
