# Generated by Django 6.0.6 on 2026-07-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('fixed', 'Fixed Amount Off')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('max_discount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('uses_total', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('uses_left', models.PositiveIntegerField(default=0)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Loyalty Program', max_length=100)),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, help_text='Points earned per 1 unit of currency spent', max_digits=8)),
                ('redemption_rate', models.DecimalField(decimal_places=4, default=0.01, help_text='Currency value of 1 point when redeeming', max_digits=8)),
                ('min_points_redeem', models.PositiveIntegerField(default=100, help_text='Minimum points needed to redeem')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Loyalty Program',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('earn', 'Earned'), ('redeem', 'Redeemed'), ('adjust', 'Manual Adjustment'), ('expire', 'Expired')], max_length=10)),
                ('points', models.IntegerField(help_text='Positive to add, negative to deduct')),
                ('reference', models.CharField(blank=True, help_text='Order number, coupon code, etc.', max_length=100)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('min_points', models.PositiveIntegerField(default=0, help_text='Points needed to reach this tier')),
                ('bonus_percent', models.DecimalField(decimal_places=2, default=0, help_text='Extra % points earned on purchases at this tier', max_digits=5)),
                ('color', models.CharField(blank=True, help_text='CSS color for UI badge', max_length=20)),
            ],
            options={
                'ordering': ['min_points'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('type', models.CharField(choices=[('buy_x_get_y', 'Buy X Get Y'), ('percent_off', 'Percentage Off'), ('fixed_off', 'Fixed Amount Off'), ('bundle', 'Bundle Deal')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('conditions', models.JSONField(default=dict, help_text='{"min_qty": 2, "product_ids": [1,2]}')),
                ('discount', models.JSONField(default=dict, help_text='{"type":"percent","value":10}')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
