from django.urls import path
from ..views.inventory import *

urlpatterns = [
    path("inventory/",InventoryListView.as_view()),
    path("inventory/test/",TestInventoryView.as_view(),),
    path("inventory/movements/",StockMovementHistoryView.as_view()),
    path("inventory/movements/<int:pk>/",StockMovementDetailView.as_view(),),
    path("inventory/movements/summary/",StockMovementSummaryView.as_view()),
    path("inventory/movements/export/csv/",StockMovementExportCSVView.as_view()),
    path("inventory/movements/export/excel/",StockMovementExportExcelView.as_view(),),
    path("inventory/movements/export/pdf/",StockMovementExportPDFView.as_view(),),
    path("inventory/summary/",InventorySummaryView.as_view(),),
    path("inventory/low-stock/",LowStockProductsView.as_view(),),
    path("inventory/products/<int:pk>/",ProductDetailView.as_view(),),
    path("inventory/dashboard/",InventoryDashboardView.as_view(),),
    path("inventory/adjustments/",StockAdjustmentView.as_view(),),
    path("inventory/stock-adjustments/",StockAdjustmentCreateView.as_view(),),
    path("inventory/stock-adjustments/history/",StockAdjustmentListView.as_view(),),
    path("inventory/stock-adjustments/<str:adjustment_number>/",StockAdjustmentDetailView.as_view(),),
    path("inventory/stock-adjustments/export/csv/",StockAdjustmentExportCSVView.as_view(),),
    path("inventory/stock-adjustments/export/excel/",StockAdjustmentExportExcelView.as_view(),),
    path("inventory/stock-adjustments/export/pdf/",StockAdjustmentExportPDFView.as_view(),),
    path("inventory/valuation/",InventoryValuationView.as_view(),),    
    path("inventory/valuation/products/",ProductInventoryValuationView.as_view(),),
    path("inventory/reports/",InventoryReportView.as_view(),),       
    path("inventory/analytics/",InventoryAnalyticsView.as_view(),),  
    path("inventory/analytics/top-selling/",TopSellingProductsView.as_view(),),
    path("inventory/analytics/slow-moving/",SlowMovingProductsView.as_view(),),
    path("inventory/analytics/most-returned/",MostReturnedProductsView.as_view(),),
    path("inventory-product/export/csv/",InventoryProductExportCSVView.as_view(),),   
    path("inventory-product/export/excel/",InventoryProductExportExcelView.as_view(),),   
    path("inventory-product/export/pdf/",InventoryProductExportPDFView.as_view(),),   
    path("inventory/products/<int:pk>/update/",ProductUpdateView.as_view(),),
]