# Generated by Django 6.0.6 on 2026-07-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fiscal', '0001_initial'),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiscalinvoice',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.customer'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiscal_invoices', to='pos.order'),
        ),
        migrations.AddField(
            model_name='fiscalsubmission',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fiscal.fiscaldevice'),
        ),
        migrations.AddField(
            model_name='fiscalsubmission',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='fiscal.fiscalinvoice'),
        ),
        migrations.AddField(
            model_name='fiscalinvoice',
            name='sequence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='fiscal.invoicesequence'),
        ),
    ]
